amazon:
    dynamodb:
       endpoint: dynamodb.ap-northeast-1.amazonaws.com
       region: ap-northeast-1
    aws:
        accesskey: AKIAWUAR7BE57W3TU4US
        secretkey: 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