spring:
   security:
      oauth2:
         client:
            provider:
               google:
                  authorization-uri: https://accounts.google.com/o/oauth2/auth
                  token-uri: https://oauth2.googleapis.com/token
            registration:
               google:
                  client-id: sampleid
                  client-secret: samplesecrete
                  scope: https://www.googleapis.com/auth/photoslibrary.readonly,https://www.googleapis.com/auth/photoslibrary,openid,profile,email
   datasource:
      url: jdbc:h2:file:./googlephotos
      driverClassName: org.h2.Driver
      username: sa
      password: null
      platform: h2
      continue-on-error: true
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      hibernate.ddl-auto: none
   h2.console:
      enabled: true
      path: /data
storage:
   directory: /home/storage
   archiveDirectory: /home/storage/archive
media.download:
   executor:
      corePoolSize: 2
      maxPoolSize: 2
      threadNamePrefix: media-downloader-
      threadNamePrefixSet: true
   completion.scheduler: null
management:
    endpoints:
       enabled-by-default: true
       web.exposure.include: '*'
    endpoint:
       beans.enabled: true
       shutdown.enabled: true
cloud.aws.region.static: us-east-1
