spring:
  security:
    oauth2:
      client:
        provider:
          google:
             authorization-uri: https://accounts.google.com/o/oauth2/auth
             token-uri: https://oauth2.googleapis.com/token
        registration:
          google:
            client-id: sampleid
            client-secret: samplesecrete
            scope: https://www.googleapis.com/auth/photoslibrary.readonly,openid
   datasource:
      url: jdbc:h2:file:./googlephotos
      driverClassName: org.h2.Driver
      username: sa
      password: 
      platform: h2
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      hibernate.ddl-auto: update
   h2.console:
      enabled: true
      path: /data
storage:
   directory: /home/storage
media.download:
   executor:
      corePoolSize: 2
      maxPoolSize: 2
      threadNamePrefix: media-downloader-
      threadNamePrefixSet: true